[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
strict-num = "0.2"
thiserror = "1"

[dev-dependencies]
bincode = "1"
ron = "0.8"

[profile.profiling]
inherits = "release"
debug = true

[profile.test]
inherits = "release"
